apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: aapb-tls
  namespace: aapb-demo
spec:
  secretName: aapb-tls-demo
  dnsNames:
    - demo.aapb.wgbh-mla.org
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
