apiVersion: apps/v1
kind: Deployment

metadata:
  labels:
    app: aapb
  name: aapb

spec:
  selector:
    matchLabels:
      app: aapb

  template:
    metadata:
      labels:
        app: aapb

    spec:
      containers:
        - name: aapb
          image: 'ghcr.io/wgbh-mla/aapb2:pr-2749'
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /log
              name: logs
            - mountPath: /usr/src/app/jetty
              name: jetty
          resources:
            limits:
              cpu: '2'
              memory: 2Gi
            requests:
              cpu: 100m
              memory: 100Mi
          envFrom:
            - configMapRef:
                name: aapb-config
      volumes:
        - name: logs
          persistentVolumeClaim:
            claimName: logs-pvc
        - name: jetty
          persistentVolumeClaim:
            claimName: jetty-pvc
